using System;
using Server;
using Server.Mobiles;

namespace Server
{
	public class OppositionGroup
	{
		private Type[][] m_Types;

		public OppositionGroup( Type[][] types )
		{
			m_Types = types;
		}

		public bool IsEnemy( object from, object target )
		{
			int fromGroup = IndexOf( from );
			int targGroup = IndexOf( target );

			return ( fromGroup != -1 && targGroup != -1 && fromGroup != targGroup );
		}

		public int IndexOf( object obj )
		{
			if ( obj == null )
				return -1;

			Type type = obj.GetType();

			for ( int i = 0; i < m_Types.Length; ++i )
			{
				Type[] group = m_Types[i];

				bool contains = false;

				for ( int j = 0; !contains && j < group.Length; ++j )
					contains = ( type == group[j] );

				if ( contains )
					return i;
			}

			return -1;
		}

		private static OppositionGroup m_TerathansAndOphidians = new OppositionGroup( new Type[][]
			{
				new Type[]
				{
					typeof( TerathanAvenger ),
					typeof( TerathanDrone ),
					typeof( TerathanMatriarch ),
					typeof( TerathanWarrior )
				},
				new Type[]
				{
					typeof( OphidianArchmage ),
					typeof( OphidianKnight ),
					typeof( OphidianMage ),
					typeof( OphidianMatriarch ),
					typeof( OphidianWarrior )
				}
			} );

		public static OppositionGroup TerathansAndOphidians
		{
			get{ return m_TerathansAndOphidians; }
		}

		private static OppositionGroup m_SavagesAndOrcs = new OppositionGroup( new Type[][]
			{
				new Type[]
				{
					typeof( Orc ),
					typeof( OrcBomber ),
					typeof( OrcBrute ),
					typeof( OrcCaptain ),
					typeof( OrcishLord ),
					typeof( OrcishMage ),
					typeof( SpawnedOrcishLord )
				},
				new Type[]
				{
					typeof( Savage ),
					typeof( SavageRider ),
					typeof( SavageRidgeback ),
					typeof( SavageShaman )
				}
			} );

		public static OppositionGroup SavagesAndOrcs
		{
			get{ return m_SavagesAndOrcs; }
		}
		
		private static OppositionGroup m_BaseVendorAndAll = new OppositionGroup( new Type[][]
		{
				new Type[]
				{
					typeof( Butcher ), // chage to your npc 
					typeof( Alchemist ),
					typeof( AnimalTrainer ),
					typeof( Architect ),
					typeof( Armorer ),
					typeof( Baker ),
					typeof( BaseHire ),
					typeof( Bard ),
					typeof( Barkeeper ),
					typeof( Beekeeper ),
					typeof( Blacksmith ),
					typeof( Bowyer ),
					typeof( Carpenter ),
					typeof( Cobbler ),
					typeof( Cook ),
					typeof( CustomHairstylist ),
					typeof( Farmer ),
					typeof( Fisherman ),
					typeof( Furtrader ),
					typeof( Glassblower ),
					typeof( GolemCrafter ),
					typeof( GypsyAnimalTrainer ),
					typeof( GypsyBanker ),
					typeof( GypsyMaiden ),
					typeof( HairStylist ),
					typeof( Herbalist ),
					typeof( HolyMage ),
					typeof( InnKeeper ),
					typeof( IronWorker ),
					typeof( Jeweler ),
					typeof( KeeperOfChivalry ),
					typeof( LeatherWorker ),
					typeof( Mage ),
					typeof( Mapmaker ),
					typeof( Miller ),
					typeof( Miner ),
					typeof( Provisioner ),
					typeof( Rancher ),
					typeof( RealEstateBroker ),
					typeof( Scribe ),
					typeof( Shipwright ),
					typeof( StoneCrafter ),
					typeof( Tailor ),
					typeof( Tanner ),
					typeof( TavernKeeper ),
					typeof( Thief ),
					typeof( Tinker ),
					typeof( Vagabond ),
					typeof( VarietyDealer ),
					typeof( Veterinarian ),
					typeof( Waiter ),
					typeof( Weaponsmith ),
					typeof( Weaver )
				},
				new Type[]
				{
					typeof( Psycho ),
					typeof( AncientLich ),
					typeof( Bogle ),
					typeof( LichLord ),
					typeof( Shade ),
					typeof( Spectre ),
					typeof( Wraith ),
					typeof( BoneKnight ),
					typeof( Ghoul ),
					typeof( Mummy ),
					typeof( SkeletalKnight ),
					typeof( Skeleton ),
					typeof( Zombie ),
					typeof( ShadowKnight ),
					typeof( DemonKnight ),
					typeof( DarknightCreeper ),
					typeof( RevenantLion ),
					typeof( LadyOfTheSnow ),
					typeof( RottingCorpse ),
					typeof( SkeletalDragon ),
					typeof( Lich ),

					//typeof( Centaur ),
					//typeof( EtherealWarrior ),
					//typeof( Kirin ),
					//typeof( LordOaks ),
					//typeof( Pixie ),
					//typeof( Silvani ),
					//typeof( Unicorn ),
					//typeof( Wisp ),
					//typeof( Treefellow ),

					typeof( Orc ),
					typeof( OrcBomber ),
					typeof( OrcBrute ),
					typeof( OrcCaptain ),
					typeof( OrcishLord ),
					typeof( OrcishMage ),
					typeof( SpawnedOrcishLord ),

					typeof( Savage ),
					typeof( SavageRider ),
					typeof( SavageRidgeback ),
					typeof( SavageShaman ),
					
					typeof( TerathanAvenger ),
					typeof( TerathanDrone ),
					typeof( TerathanMatriarch ),
					typeof( TerathanWarrior ),
					typeof( OphidianArchmage ),
					typeof( OphidianKnight ),
					typeof( OphidianMage ),
					typeof( OphidianMatriarch ),
					typeof( OphidianWarrior ),

					//typeof( BlackBear ),
					//typeof( BrownBear ),
					//typeof( GrizzlyBear ),
					//typeof( PolarBear ),
					//typeof( Eagle ),
					//typeof( Phoenix ),
					typeof( DireWolf ),
					//typeof( GreyWolf ),
					//typeof( TimberWolf ),
					//typeof( WhiteWolf ),
					//typeof( Bull ),
					//typeof( Cougar ),
					typeof( HellCat ),
					//typeof( Panther ),
					typeof( PredatorHellCat ),
					//typeof( SnowLeopard ),
					//typeof( Boar ),
					//typeof( Dolphin ),
					//typeof( Gaman ),
					//typeof( GiantToad ),
					//typeof( Gorilla ),
					//typeof( Llama ),
					//typeof( MountainGoat ),
					//typeof( PackHorse ),
					//typeof( PackLlama ),
					//typeof( Walrus ),
					//typeof( Beetle ),
					//typeof( DesertOstard ),
					//typeof( ForestOstard ),
					//typeof( FrenziedOstard ),
					//typeof( FireSteed ),
					//typeof( HellSteed ),
					typeof( Hiryu ),
					typeof( BlackSolenInfiltratorQueen ),
					typeof( LesserHiryu ),
					typeof( Nightmare ),
					//typeof( RidableLlama ),
					typeof( Ridgeback ),
					typeof( SavageRidgeback ),
					typeof( ScaledSwampDragon ),
					//typeof( SeaHorse ),
					//typeof( SilverSteed ),
					typeof( SkeletalMount ),
					typeof( SwampDragon ),
					typeof( AntLion ),
					typeof( CoMWarHorse ),
					typeof( MinaxWarHorse ),
					typeof( SLWarHorse ),
					typeof( TBWarHorse ),
					//typeof( Alligator ),
					typeof( GiantSerpent ),
					typeof( IceSerpent ),
					typeof( IceSnake ),
					typeof( LavaLizard ),
					typeof( LavaSerpent ),
					typeof( LavaSnake ),
					typeof( SilverSerpent ),
					typeof( Snake ),
					typeof( GiantRat ),
					typeof( Sewerrat ),
					typeof( Jwilson ),
					typeof( DarkWolfFamiliar ),
					typeof( DeathAdder ),
					typeof( HordeMinionFamiliar ),
					typeof( ShadowWisp ),
					typeof( VampireBat ),
					typeof( ArcherGuard ),
					typeof( WarriorGuard ),
					typeof( EvilHealer ),
					typeof( EvilWanderingHealer ),
					typeof( FortuneTeller ),
					//typeof( Healer ),
					typeof( PricedHealer ),
					//typeof( WanderingHealer ),
					typeof( Barracoon ),
					typeof( ChaosGuard ),
					typeof( Harrower ),
					typeof( HarrowerTentacles ),
					typeof( LordOaks ),
					typeof( Mephitis ),
					typeof( Neira ),
					typeof( OrderGuard ),
					typeof( Rikktor ),
					typeof( Semidar ),
					typeof( Serado ),
					typeof( ServantOfSemidar ),
					typeof( BlackSolenInfiltratorWarrior ),
					typeof( BlackSolenQueen ),
					typeof( BlackSolenWarrior ),
					typeof( BlackSolenWorker ),
					typeof( RedSolenInfiltratorQueen ),
					typeof( RedSolenInfiltratorWarrior ),
					typeof( RedSolenQueen ),
					typeof( RedSolenWarrior ),
					typeof( RedSolenWorker ),
					typeof( AbysmalHorror ),
					typeof( BoneDemon ),
					typeof( Devourer ),
					typeof( FleshGolem ),
					typeof( FleshRenderer ),
					typeof( Gibberling ),
					typeof( GoreFiend ),
					typeof( Impaler ),
					typeof( MoundOfMaggots ),
					typeof( PatchworkSkeleton ),
					typeof( Ravager ),
					typeof( Revenant ),
					typeof( SkitteringHopper ),
					typeof( VampireBat ),
					typeof( WailingBanshee ),
					typeof( WandererOfTheVoid ),
					typeof( DreadSpider ),
					typeof( FrostSpider ),
					typeof( GiantBlackWidow ),
					typeof( GiantSpider ),
					typeof( AirElemental ),
					typeof( IceElemental ),
					typeof( ToxicElemental ),
					typeof( PoisonElemental ),
					typeof( FireElemental ),
					typeof( WaterElemental ),
					typeof( EarthElemental ),
					typeof( Efreet ),
					typeof( SnowElemental ),
					typeof( AgapiteElemental ),
					typeof( BronzeElemental ),
					typeof( CopperElemental ),
					typeof( DullCopperElemental ),
					typeof( GoldenElemental ),
					typeof( ShadowIronElemental ),
					typeof( ValoriteElemental ),
					typeof( VeriteElemental ),
					typeof( ArcaneDaemon ),
					typeof( Balron ),
					typeof( Betrayer ),
					typeof( BoneMagi ),
					typeof( ElderGazer ),
					typeof( EvilMage ),
					typeof( EvilMageLord ),
					typeof( Gargoyle ),
					typeof( GargoyleDestroyer ),
					typeof( GargoyleEnforcer ),
					typeof( Gazer),
					typeof( GolemController ),
					typeof( IceFiend ),
					typeof( Imp ),
					typeof( OrcishMage ),
					typeof( RatmanMage ),
					typeof( SkeletalMage ),
					typeof( Succubus ),
					typeof( Titan ),
					typeof( ArcticOgreLord ),
					typeof( Brigand ),
					typeof( ChaosDaemon ),
					typeof( Cursed ),
					typeof( Cyclops ),
					typeof( Doppleganger ),
					typeof( EnslavedGargoyle ),
					typeof( Ettin ),
					typeof( Executioner ),
					typeof( FrostTroll ),
					typeof( GazerLarva ),
					typeof( HeadlessOne ),
					typeof( Juggernaut ),
					typeof( KhaldunRevenant ),
					typeof( KhaldunSummoner ),
					typeof( KhaldunZealot ),
					typeof( Moloch ),
					typeof( Mongbat ),
					typeof( Mummy ),
					typeof( Ogre ),
					typeof( OgreLord ),
					typeof( Ratman ),
					typeof( RatmanArcher ),
					typeof( RestlessSoul ),
					typeof( WhiteWyrm ),
					typeof( ShadowFiend ),
					typeof( SpectralArmour ),
					typeof( StoneGargoyle ),
					typeof( StrongMongbat ),
					typeof( Troll ),
					typeof( ExodusMinion ),
					typeof( ExodusOverseer ),
					typeof( JukaLord ),
					typeof( JukaMage ),
					typeof( JukaWarrior ),
					typeof( MeerCaptain ),
					typeof( MeerEternal ),
					typeof( MeerMage ),
					typeof( MeerWarrior ),
					typeof( HellHound ),
					typeof( VorpalBunny ),
					typeof( DarkWisp ),
					typeof( BladeSpirits ),
					typeof( EnergyVortex ),
					typeof( FrostOoze ),
					typeof( Golem ),
					typeof( PlagueBeast ),
					typeof( PlagueSpawn ),
					typeof( SandVortex ),
					typeof( Slime ),
					typeof( Reaper ),
					typeof( BogThing ),
					typeof( Bogling ),
					typeof( Corpser ),
					typeof( Quagmire ),
					typeof( SwampTentacle ),
					typeof( WhippingVine ),
					typeof( AncientWyrm ),
					typeof( DeepSeaSerpent ),
					typeof( Dragon ),
					typeof( Leviathan ),
					typeof( SerpentineDragon ),
					typeof( ShadowWyrm ),
					typeof( Drake ),
					typeof( Harpy ),
					typeof( Kraken ),
					typeof( Lizardman ),
					typeof( Scorpion ),
					typeof( StoneHarpy ),
					typeof( Wyvern ),
					typeof( DeathwatchBeetle ),
					typeof( DeathwatchBeetleHatchling ),
					typeof( EliteNinja ),
					typeof( FanDancer ),
					typeof( FireBeetle ),
					typeof( Kappa ),
					typeof( KazeKemono ),
					typeof( Oni ),
					typeof( RaiJu ),
					typeof( Ronin ),
					typeof( RuneBeetle ),
					typeof( TsukiWolf ),
					typeof( YomotsuWarrior ),
					typeof( Yamandon),
					typeof( YomotsuElder ),
					typeof( YomotsuPriest ),
					typeof( SummonedAirElemental ),
					typeof( SummonedEarthElemental ),
					typeof( SummonedFireElemental ),
					typeof( SummonedWaterElemental ),
					typeof( SummonedDaemon ),
					//typeof( abscess ),
					//typeof( Changeling ),
					//typeof( Chimera ),
					//typeof( Coil ),
					//typeof( Crow ),
					//typeof( CuSidhe ),
					//typeof( DreadHorn ),
					//typeof( DryadA ),
					//typeof( ferret ),
					//typeof( FetidEssence ),
					//typeof( Grobu ),
					//typeof( Hydra ),
					//typeof( InsaneDryad ),
					//typeof( InterredGrizzle ),
					//typeof( LadyMelisande ),
					//typeof( LeatherArmoredMinotaur ),
					//typeof( ParrotA ),
					//typeof( Lurg ),
					//typeof( Minotaur ),
					//typeof( MonstrousInterredGrizzle ),
					//typeof( PlateArmoredMinotaur ),
					//typeof( ReaperForm ),
					//typeof( ShimmeringEffusion ),
					//typeof( squirrel ),
					//typeof( Tangle ),
					//typeof( Thrasher ),
					//typeof( TormentedMinotaur ),
					//typeof( Travesty ),
					//typeof( Troglodyte ),
					//typeof( IceHound ),
					//typeof( Chicken ),
					//typeof( Crane ),
					//typeof( Cow ),
					//typeof( BullFrog ),
					//typeof( Hind ),
					//typeof( GreatHart ),
					//typeof( Pig ),
					//typeof( JackRabbit ),
					//typeof( Sheep ),
					//typeof( Goat ),
					//typeof( Rabbit ),
					//typeof( Horse ),
					//typeof( Cat ),
					//typeof( Bird ),
					//typeof( Rat ),
					//typeof( Dog ),
					//typeof( Balrog ),
					typeof( Daemon )
				}
			} 
		);
		
		public static OppositionGroup BaseVendorAndAll
		{
			get{ return m_BaseVendorAndAll; }
		}
		
		private static OppositionGroup m_FeyAndUndead = new OppositionGroup( new Type[][]
			{
				new Type[]
				{
					typeof( Centaur ),
					typeof( EtherealWarrior ),
					typeof( Kirin ),
					typeof( LordOaks ),
					typeof( Pixie ),
					typeof( Silvani ),
					typeof( Unicorn ),
					typeof( Wisp ),
					typeof( Treefellow ),
					typeof( MLDryad ),
					typeof( Butcher ), // chage to your npc 
					typeof( Alchemist ),
					typeof( AnimalTrainer ),
					typeof( Architect ),
					typeof( Armorer ),
					typeof( Baker ),
					typeof( Bard ),
					typeof( Barkeeper ),
					typeof( Beekeeper ),
					typeof( Blacksmith ),
					typeof( Bowyer ),
					typeof( Carpenter ),
					typeof( Cobbler ),
					typeof( Cook ),
					typeof( CustomHairstylist ),
					typeof( Farmer ),
					typeof( Fisherman ),
					typeof( Furtrader ),
					typeof( Glassblower ),
					typeof( GolemCrafter ),
					typeof( GypsyAnimalTrainer ),
					typeof( GypsyBanker ),
					typeof( GypsyMaiden ),
					typeof( HairStylist ),
					typeof( Herbalist ),
					typeof( HolyMage ),
					typeof( InnKeeper ),
					typeof( IronWorker ),
					typeof( Jeweler ),
					typeof( KeeperOfChivalry ),
					typeof( LeatherWorker ),
					typeof( Mage ),
					typeof( Mapmaker ),
					typeof( Miller ),
					typeof( Miner ),
					typeof( Provisioner ),
					typeof( Rancher ),
					typeof( RealEstateBroker ),
					typeof( Scribe ),
					typeof( Shipwright ),
					typeof( StoneCrafter ),
					typeof( Tailor ),
					typeof( Tanner ),
					typeof( TavernKeeper ),
					typeof( Thief ),
					typeof( Tinker ),
					typeof( Vagabond ),
					typeof( VarietyDealer ),
					typeof( Veterinarian ),
					typeof( Waiter ),
					typeof( Weaponsmith ),
					typeof( Weaver )
				},
				new Type[]
				{
					typeof( Psycho ),
					typeof( AncientLich ),
					typeof( Bogle ),
					typeof( LichLord ),
					typeof( Shade ),
					typeof( Spectre ),
					typeof( Wraith ),
					typeof( BoneKnight ),
					typeof( Ghoul ),
					typeof( Mummy ),
					typeof( SkeletalKnight ),
					typeof( Skeleton ),
					typeof( Zombie ),
					typeof( ShadowKnight ),
					typeof( DarknightCreeper ),
					typeof( RevenantLion ),
					typeof( LadyOfTheSnow ),
					typeof( RottingCorpse ),
					typeof( SkeletalDragon ),
					typeof( Lich )
				}
			} );

		public static OppositionGroup FeyAndUndead
		{
			get{ return m_FeyAndUndead; }
		}
	}
}